version: '3.8'
services:
  frontend:
    image: YOUR_DOCKER_USERNAME/fusionpact-frontend:latest
    ports:
      - "80:80"
    restart: always

  backend:
    image: YOUR_DOCKER_USERNAME/fusionpact-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/app/data
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always

volumes:
  backend_data: